"""Pure-compute voice-activity-detection tool capability using Silero VAD (Option C, stage 8).

Docs: https://cj-mills.github.io/cjm-media-plugin-silero-vadplugin.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/plugin.ipynb.

# %% auto #0
__all__ = ['SileroVADConfig', 'SileroVADPlugin']

# %% ../nbs/plugin.ipynb #fe7e7229
import logging
from dataclasses import dataclass, field
from typing import Dict, Any, Optional, List, Union, Tuple, ClassVar
from pathlib import Path

import numpy as np
import soundfile as sf

# Stage 8 (Option C / PILLAR 1c): the tool re-bases onto ToolCapability (pure
# compute). The cache/persist bookends + the VADResult data noun moved OUT — the
# generic adapter (cjm-vad-adapter-interface) owns the cache, and the result DTO
# lives in cjm-capability-primitives. No get_plugin_metadata, no self.storage,
# no librosa: audio arrives MODEL-READY (mono 8k/16k, converted upstream by
# ffmpeg with the soxr resampler), so the tool just reads it via soundfile.
from cjm_plugin_system.core.capability import ToolCapability, RELOAD_TRIGGER, EnvVarSpec
from cjm_capability_primitives.vad import VADResult, TimeRange
from cjm_plugin_system.core.errors import PluginInputError, PluginFatalError
from cjm_plugin_system.utils.validation import (
    dict_to_config, config_to_dict, dataclass_to_jsonschema,
    SCHEMA_TITLE, SCHEMA_DESC, SCHEMA_MIN, SCHEMA_MAX
)

# Silero Imports
try:
    from silero_vad import load_silero_vad, get_speech_timestamps
    SILERO_AVAILABLE = True
except ImportError:
    SILERO_AVAILABLE = False

# %% ../nbs/plugin.ipynb #b810b57b
@dataclass
class SileroVADConfig:
    """Configuration for Silero VAD parameters."""
    
    threshold: float = field(
        default=0.5,
        metadata={
            SCHEMA_TITLE: "Threshold",
            SCHEMA_DESC: "Speech probability threshold (0.0 - 1.0). Higher values reduce false positives.",
            SCHEMA_MIN: 0.0, SCHEMA_MAX: 1.0
        }
    )
    
    min_speech_duration_ms: int = field(
        default=250,
        metadata={
            SCHEMA_TITLE: "Min Speech Duration (ms)",
            SCHEMA_DESC: "Segments shorter than this will be ignored.",
            SCHEMA_MIN: 0
        }
    )
    
    min_silence_duration_ms: int = field(
        default=100,
        metadata={
            SCHEMA_TITLE: "Min Silence Duration (ms)",
            SCHEMA_DESC: "Silence shorter than this will not split segments.",
            SCHEMA_MIN: 0
        }
    )
    
    speech_pad_ms: int = field(
        default=30,
        metadata={
            SCHEMA_TITLE: "Speech Padding (ms)",
            SCHEMA_DESC: "Padding added to the start/end of each speech segment.",
            SCHEMA_MIN: 0
        }
    )
    
    use_onnx: bool = field(
        default=True,
        metadata={
            SCHEMA_TITLE: "Use ONNX",
            SCHEMA_DESC: "Use ONNX runtime for inference (faster).",
            RELOAD_TRIGGER: "model"  # CR-4: switching backend invalidates the loaded model
        }
    )

# %% ../nbs/plugin.ipynb #ea0dda6a
class SileroVADPlugin(ToolCapability):
    """Voice Activity Detection tool capability using Silero VAD (stage 8: pure compute).

    Native-surface model (PILLAR 1c): this tool is PURE COMPUTE — `detect_speech`
    reads MODEL-READY audio, runs Silero inference, and builds the typed
    `VADResult`. The cache-check + persistence bookends + the per-call `force`
    control live in the generic VAD adapter (cjm-vad-adapter-interface); the
    result DTO lives in cjm-capability-primitives; identity is derived from the
    installed distribution. No `get_plugin_metadata`, no `self.storage`, no
    librosa (decode/resample is upstream ffmpeg, soxr)."""

    # CR-4: declarative reload-triggers — substrate's reconfigure_with_triggers
    # walks config_class for RELOAD_TRIGGER metadata and fires _release_<trigger>.
    config_class = SileroVADConfig

    # Track 19 (CR-12 worker-env model): worker spawn env declared on the class.
    WORKER_ENV: ClassVar[List[EnvVarSpec]] = [
        EnvVarSpec(
            name="OMP_NUM_THREADS",
            default="4",
            label="OpenMP Threads",
            description="Thread cap for CPU-side numerical ops.",
        ),
    ]

    def __init__(self):
        """Initialize the Silero VAD plugin."""
        self.logger = logging.getLogger(f"{__name__}.{type(self).__name__}")
        self.config: SileroVADConfig = None
        self._model = None

    @property
    def name(self) -> str:  # Plugin name identifier
        """Plugin identity, derived from the installed distribution (PILLAR 1c)."""
        from importlib.metadata import metadata, packages_distributions
        dist = (packages_distributions().get(__package__) or [__package__.replace("_", "-")])[0]
        return metadata(dist)["Name"]

    @property
    def version(self) -> str:  # Plugin version string
        """Get the plugin version string."""
        from cjm_media_plugin_silero_vad import __version__
        return __version__

    def get_current_config(self) -> Dict[str, Any]:  # Current configuration as dictionary
        """Return current configuration state."""
        return config_to_dict(self.config) if self.config else {}

    def get_config_schema(self) -> Dict[str, Any]:  # JSON Schema for configuration
        """Return JSON Schema for UI generation."""
        return dataclass_to_jsonschema(SileroVADConfig)

    def _apply_config(
        self,
        config: Optional[Any] = None  # Configuration dataclass, dict, or None
    ) -> None:
        """CR-4: apply config values only (no heavy-resource work). Called by
        initialize (first-time) and by the substrate's reconfigure delta path."""
        self.config = dict_to_config(SileroVADConfig, config or {})

    def initialize(
        self,
        config: Optional[Any] = None  # Configuration dataclass, dict, or None
    ) -> None:
        """First-time setup. CR-4: config application is factored into _apply_config;
        the substrate's reconfigure(old, new) fires _release_model on a use_onnx
        change (RELOAD_TRIGGER) then re-applies config. No storage init — the
        adapter owns the cache (stage 8)."""
        self._apply_config(config)
        self.logger.info(f"Initialized Silero VAD plugin with threshold={self.config.threshold}")

    def _load_model(self) -> None:
        """Lazy load the Silero model."""
        if self._model is None:
            if not SILERO_AVAILABLE:
                raise PluginFatalError(  # SG-47: load-time dependency missing — fatal until operator installs silero-vad
                    "silero-vad not installed.",
                )
            self.logger.info("Loading Silero VAD model")
            self._model = load_silero_vad(onnx=self.config.use_onnx)
            self.logger.info("Silero VAD model loaded successfully")

    def _release_model(self) -> None:
        """CR-4: release the loaded VAD model. RELOAD_TRIGGER target for `use_onnx`;
        on_disable / cleanup delegate here. Guarded so a redundant call is a no-op."""
        if self._model is not None:
            self.logger.info("Releasing Silero VAD model")
            self._model = None

    def _prepare_audio(
        self,
        audio: Union[str, Path]  # Path to a MODEL-READY audio file
    ) -> str:  # The audio file path
        """Validate the audio input and return it as a path string.

        The caller (orchestration / adapter) guarantees a MODEL-READY audio file
        (mono, 8k/16k — converted upstream by ffmpeg); in-tool decode/resample is
        no longer a plugin responsibility."""
        if isinstance(audio, (str, Path)):
            return str(audio)
        raise PluginInputError(  # SG-47: typed input-validation
            f"Unsupported audio input type: {type(audio)}; expected a file path (str or Path)",
            fields_invalid=["audio"],
        )

    def _load_audio(
        self,
        path: str  # Path to a model-ready audio file
    ) -> Tuple[np.ndarray, int, float]:  # (mono float32 samples, sample rate, duration in seconds)
        """Read MODEL-READY audio via soundfile (no resample — conversion is upstream).

        Returns mono float32 samples peak-normalized to [-1, 1], the file's sample
        rate, and the duration. Validates the rate is one Silero supports (8k/16k);
        a wrong rate means the upstream convert is misconfigured."""
        y, sr = sf.read(path, dtype="float32", always_2d=False)
        if y.ndim > 1:                       # defensive mono-mix (the convert emits mono)
            y = y.mean(axis=1).astype(np.float32)
        if sr not in (8000, 16000):
            raise PluginInputError(  # upstream convert misconfigured — Silero needs 8k/16k
                f"Silero VAD requires 8k or 16k model-ready audio; got {sr} Hz "
                f"(convert upstream). Path: {path}",
                fields_invalid=["audio"],
            )
        peak = float(np.max(np.abs(y))) if len(y) else 0.0
        if peak > 0:
            y = (y / peak).astype(np.float32)
        return y, sr, float(len(y) / sr)

    def detect_speech(
        self,
        audio: Union[str, Path],  # Path to MODEL-READY audio (mono 8k/16k, converted upstream)
        **kwargs                  # Provenance pass-through (unused by VAD compute)
    ) -> VADResult:  # Typed VAD output with detected speech segments
        """Detect speech segments in model-ready audio — PURE COMPUTE.

        Stage 8 / PILLAR 1c: the cache-check + persistence bookends + the per-call
        `force` control moved to the generic VAD adapter; this method reads the
        audio, runs Silero, and builds the typed result. Detection params come
        from `self.config` (no per-call kwarg override — the tool runs its
        effective config)."""
        audio_path = self._prepare_audio(audio)
        self._load_model()

        self.logger.info(f"Processing audio: {audio_path}")
        wav, sr, duration = self._load_audio(audio_path)

        speech_timestamps = get_speech_timestamps(
            audio=wav,
            model=self._model,
            threshold=self.config.threshold,
            sampling_rate=sr,
            min_speech_duration_ms=self.config.min_speech_duration_ms,
            min_silence_duration_ms=self.config.min_silence_duration_ms,
            speech_pad_ms=self.config.speech_pad_ms,
            return_seconds=True,  # Critical: We want seconds, not samples
            visualize_probs=False
        )

        ranges = [
            TimeRange(start=ts["start"], end=ts["end"], label="speech", confidence=1.0)
            for ts in speech_timestamps
        ]
        total_speech = sum(r.end - r.start for r in ranges)
        metadata = {
            "duration": duration,
            "sample_rate": sr,
            "total_speech": total_speech,
            "total_silence": duration - total_speech,
            "segment_count": len(ranges),
        }
        self.logger.info(
            f"Detected {len(ranges)} speech segments "
            f"({total_speech:.2f}s speech / {duration:.2f}s total)"
        )
        return VADResult(ranges=ranges, metadata=metadata)

    def is_available(self) -> bool:  # True if Silero VAD is available
        """Check if Silero VAD is available."""
        return SILERO_AVAILABLE

    def prefetch(self) -> None:
        """CR-4 (SG-19): eagerly load the model so the first call doesn't pay the load cost."""
        self._load_model()

    def on_disable(self) -> None:
        """CR-2: release the model when the operator disables the plugin (worker stays alive)."""
        self._release_model()

    def cleanup(self) -> None:
        """Release resources on unload."""
        self._release_model()
